name: petlendar
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  intl: ^0.20.2
  get: ^4.7.2
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
flutter_icons:
  android: true
  ios: false
  image_path: "assets/src/petlendar.png"